spring:
  application:
    name: accountservice
  datasource:
    url: jdbc:postgresql://localhost:5432/AccountDb
    username: postgres
    password: test

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    registeredWithEureka: true
    fetchRegistry: true
