spring:
  application:
    name: authService
  datasource:
    url: jdbc:postgresql://localhost:5432/demo2Db
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    registeredWithEureka: true
    fetchRegistry: true